services:

  caddy:
    image: caddy:2.9.1-alpine
    restart: unless-stopped
    ports:
      - "${CADDY_PORT}:${CADDY_PORT}"
      - "${CADDY_PORT_SSL}:${CADDY_PORT_SSL}"
    volumes:
      - ./caddy:/etc/caddy
      - caddy_data:/data
      - caddy_config:/config
    env_file:
      -  .env
    networks:
      - works-network

  postgres:
    image: postgres:17.2-alpine
    restart: always
    env_file:
      -  .env
    networks:
      - works-network

  todo-list:
    build: ../todo-list
    restart: always
    networks:
      - works-network

volumes:
  caddy_data:
  caddy_config:

networks:
  works-network:
    driver: bridge
    